export const profileData = {
  _id: 123123,
  userName: 'Jane Dave',
  level: 'Intermediate',
  role: 'Student',
  year: '2024',
  email: 'jane@gmx.com',
  phone: '+91-1234567890',
  joiningDate: '20/05/2024',
  profilePicture: 'https://picsum.photos/id/91/200/300',
  location: 'House#1, First Cross Road, New York, New York - 100123',
  certificates: [
    {
      title: 'Basic Physics',
      description: 'Course Completion',
      image: 'https://picsum.photos/id/235/200/100',
      downloadLink: '#',
      shareLink: '#',
    },
    {
      title: 'Advanced Physics',
      description: 'Course Completion',
      image: 'https://picsum.photos/id/36/200/100',
      downloadLink: '#',
      shareLink: '#',
    },
  ],
  courses: [
    {
      title: 'MERN STACK',
      type: 'Live class',
      duration: 40,
      progress: 0,
      image: 'https://picsum.photos/id/563/200/100',
      sessionLink: '#',
    },
    {
      title: 'DevOPS with AWS',
      type: 'Self-study',
      duration: 30,
      progress: 55,
      image: 'https://picsum.photos/id/672/200/100',
      sessionLink: '#',
    },
    {
      title: 'Cyber Security with python',
      type: 'Self-study',
      duration: 20,
      progress: 100,
      image: 'https://picsum.photos/id/341/200/100',
      sessionLink: '#',
    },
    {
      title: 'Basic of Chat GPT',
      type: 'Self-study',
      duration: 6,
      progress: 100,
      image: 'https://picsum.photos/id/119/200/100',
      sessionLink: '#',
    },
  ],
};
